#!/bin/sh
APPDIR=`dirname $0`;
java  -Xmx256M -cp "$APPDIR/src:$APPDIR/bin:/home/zapreevis/Tools/gwt-linux-1.5.2/gwt-user.jar:/home/zapreevis/Tools/gwt-linux-1.5.2/gwt-dev-linux.jar" com.google.gwt.dev.GWTCompiler "$APPDIR/www" "$@" com.xcurechat.XCureChatMain;
