/**
 * X-Cure-Chat
 * Copyright (C) 2013  Dr. Ivan S. Zapreev
 * www: https://nl.linkedin.com/in/zapreevis
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.#
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * The user data objects package.
 * (C) Ivan S. Zapreev, 2008
 */
package com.xcurechat.client.data;

/**
 * @author zapreevis
 * The client-side user-data object for the logged-on user. Contains extended user data
 */
public class MainUserData extends UserData {
	//The user-session id, is needed after the user is logged on 
	private String userSessionId = "";
	
	//The date when the user has logged in, this is only used on the
	//server side for the sake of tracking the user online time 
	private final transient long loginTimeMillisec = System.currentTimeMillis();
	
	/**
	 * The default constructor, is needed for serialization
	 */
	public MainUserData(){
		super();
	}
	
	/**
	 * @return the user-session id generated by the server on log on
	 * it is needed after the user is logged on, to identify the use session.
	 */
	public String getUserSessionId(){
		return this.userSessionId;
	}
	
	/**
	 * @param userSessionId the user-session id generated by the server on log on
	 * it is needed after the user is logged on, to identify the use session.
	 */
	public void setUserSessionId( String userSessionId ){
		this.userSessionId = userSessionId;
	}
	
	/**
	 * Returns the time at which the user has logged in in milliseconds
	 * @return the time the user has logged in in milliseconds
	 */
	public long getLoginTime() {
		return loginTimeMillisec;
	}
}
